### ISSUE TITLE
Seems to work with current wireshark

### ISSUE THREAD

**Issue by triptec** [plietar/spotify-analyze#1]
i just updated dissect.sh with /Applications/Wireshark.app/Contents/MacOS/Wireshark and I'd say it works. That was after a few failed attempts compiling your wireshark fork though.

**Comment by plietar** [comment]
Indeed, the bug was fixed upstream (https://github.com/wireshark/wireshark/commit/38682523f9ce3ed378c782a848ba1ba5a6fe430f)
 I'll update the README.

Thanks for letting me know
